### ISSUE TITLE
Email Errors (FreeScribe)

### ISSUE THREAD

**Issue by ItsSimko** [ClinicianFOCUS/FreeScribe#74]

**Comment by ItsSimko** [comment]
Email errors from Dr. Hendy

**Comment by ItsSimko** [comment]
Traceback (most recent call last):
  File "C:\Users\braed\AppData\Local\Programs\Python\Python310\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "C:\Users\braed\Downloads\FreeScribe-main\src\FreeScribe.client\UI\SettingsWindowUI.py", line 138, in <lambda>
    self.settings_window.bind_all("<MouseWheel>", lambda e: canvas.yview_scroll(int(-1*(e.delta/120)), "units"))
  File "C:\Users\braed\AppData\Local\Programs\Python\Python310\lib\tkinter\__init__.py", line 1967, in yview_scroll
    self.tk.call(self._w, 'yview', 'scroll', number, what)
_tkinter.TclError: invalid command name ".!toplevel6.!frame.!notebook.!frame4.!canvas"
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\braed\AppData\Local\Programs\Python\Python310\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "C:\Users\braed\Downloads\FreeScribe-main\src\FreeScribe.client\UI\SettingsWindowUI.py", line 138, in <lambda>
    self.settings_window.bind_all("<MouseWheel>", lambda e: canvas.yview_scroll(int(-1*(e.delta/120)), "units"))
  File "C:\Users\braed\AppData\Local\Programs\Python\Python310\lib\tkinter\__init__.py", line 1967, in yview_scroll
    self.tk.call(self._w, 'yview', 'scroll', number, what)
_tkinter.TclError: invalid command name ".!toplevel6.!frame.!notebook.!frame4.!canvas"
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\braed\AppData\Local\Programs\Python\Python310\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "C:\Users\braed\Downloads\FreeScribe-main\src\FreeScribe.client\UI\SettingsWindowUI.py", line 138, in <lambda>
    self.settings_window.bind_all("<MouseWheel>", lambda e: canvas.yview_scroll(int(-1*(e.delta/120)), "units"))
  File "C:\Users\braed\AppData\Local\Programs\Python\Python310\lib\tkinter\__init__.py", line 1967, in yview_scroll
    self.tk.call(self._w, 'yview', 'scroll', number, what)
_tkinter.TclError: invalid command name ".!toplevel6.!frame.!notebook.!frame4.!canvas"
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\braed\AppData\Local\Programs\Python\Python310\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "C:\Users\braed\Downloads\FreeScribe-main\src\FreeScribe.client\UI\SettingsWindowUI.py", line 138, in <lambda>
    self.settings_window.bind_all("<MouseWheel>", lambda e: canvas.yview_scroll(int(-1*(e.delta/120)), "units"))
  File "C:\Users\braed\AppData\Local\Programs\Python\Python310\lib\tkinter\__init__.py", line 1967, in yview_scroll
    self.tk.call(self._w, 'yview', 'scroll', number, what)
_tkinter.TclError: invalid command name ".!toplevel6.!frame.!notebook.!frame4.!canvas"
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\braed\AppData\Local\Programs\Python\Python310\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "C:\Users\braed\Downloads\FreeScribe-main\src\FreeScribe.client\UI\SettingsWindowUI.py", line 138, in <lambda>
    self.settings_window.bind_all("<MouseWheel>", lambda e: canvas.yview_scroll(int(-1*(e.delta/120)), "units"))
  File "C:\Users\braed\AppData\Local\Programs\Python\Python310\lib\tkinter\__init__.py", line 1967, in yview_scroll
    self.tk.call(self._w, 'yview', 'scroll', number, what)
_tkinter.TclError: invalid command name ".!toplevel6.!frame.!notebook.!frame4.!canvas"
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\braed\AppData\Local\Programs\Python\Python310\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "C:\Users\braed\Downloads\FreeScribe-main\src\FreeScribe.client\UI\SettingsWindowUI.py", line 138, in <lambda>
    self.settings_window.bind_all("<MouseWheel>", lambda e: canvas.yview_scroll(int(-1*(e.delta/120)), "units"))
  File "C:\Users\braed\AppData\Local\Programs\Python\Python310\lib\tkinter\__init__.py", line 1967, in yview_scroll
    self.tk.call(self._w, 'yview', 'scroll', number, what)
_tkinter.TclError: invalid command name ".!toplevel6.!frame.!notebook.!frame4.!canvas"
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\braed\AppData\Local\Programs\Python\Python310\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "C:\Users\braed\Downloads\FreeScribe-main\src\FreeScribe.client\UI\SettingsWindowUI.py", line 138, in <lambda>
    self.settings_window.bind_all("<MouseWheel>", lambda e: canvas.yview_scroll(int(-1*(e.delta/120)), "units"))
  File "C:\Users\braed\AppData\Local\Programs\Python\Python310\lib\tkinter\__init__.py", line 1967, in yview_scroll
    self.tk.call(self._w, 'yview', 'scroll', number, what)
_tkinter.TclError: invalid command name ".!toplevel6.!frame.!notebook.!frame4.!canvas"
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\braed\AppData\Local\Programs\Python\Python310\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "C:\Users\braed\Downloads\FreeScribe-main\src\FreeScribe.client\UI\SettingsWindowUI.py", line 138, in <lambda>
    self.settings_window.bind_all("<MouseWheel>", lambda e: canvas.yview_scroll(int(-1*(e.delta/120)), "units"))
  File "C:\Users\braed\AppData\Local\Programs\Python\Python310\lib\tkinter\__init__.py", line 1967, in yview_scroll
    self.tk.call(self._w, 'yview', 'scroll', number, what)
_tkinter.TclError: invalid command name ".!toplevel6.!frame.!notebook.!frame4.!canvas"
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\braed\AppData\Local\Programs\Python\Python310\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "C:\Users\braed\Downloads\FreeScribe-main\src\FreeScribe.client\UI\SettingsWindowUI.py", line 138, in <lambda>
    self.settings_window.bind_all("<MouseWheel>", lambda e: canvas.yview_scroll(int(-1*(e.delta/120)), "units"))
  File "C:\Users\braed\AppData\Local\Programs\Python\Python310\lib\tkinter\__init__.py", line 1967, in yview_scroll
    self.tk.call(self._w, 'yview', 'scroll', number, what)
_tkinter.TclError: invalid command name ".!toplevel6.!frame.!notebook.!frame4.!canvas"
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\braed\AppData\Local\Programs\Python\Python310\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "C:\Users\braed\Downloads\FreeScribe-main\src\FreeScribe.client\UI\SettingsWindowUI.py", line 138, in <lambda>
    self.settings_window.bind_all("<MouseWheel>", lambda e: canvas.yview_scroll(int(-1*(e.delta/120)), "units"))
  File "C:\Users\braed\AppData\Local\Programs\Python\Python310\lib\tkinter\__init__.py", line 1967, in yview_scroll
    self.tk.call(self._w, 'yview', 'scroll', number, what)
_tkinter.TclError: invalid command name ".!toplevel6.!frame.!notebook.!frame4.!canvas"
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\braed\AppData\Local\Programs\Python\Python310\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "C:\Users\braed\Downloads\FreeScribe-main\src\FreeScribe.client\UI\SettingsWindowUI.py", line 138, in <lambda>
    self.settings_window.bind_all("<MouseWheel>", lambda e: canvas.yview_scroll(int(-1*(e.delta/120)), "units"))
  File "C:\Users\braed\AppData\Local\Programs\Python\Python310\lib\tkinter\__init__.py", line 1967, in yview_scroll
    self.tk.call(self._w, 'yview', 'scroll', number, what)
_tkinter.TclError: invalid command name ".!toplevel6.!frame.!notebook.!frame4.!canvas"
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\braed\AppData\Local\Programs\Python\Python310\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "C:\Users\braed\Downloads\FreeScribe-main\src\FreeScribe.client\UI\SettingsWindowUI.py", line 138, in <lambda>
    self.settings_window.bind_all("<MouseWheel>", lambda e: canvas.yview_scroll(int(-1*(e.delta/120)), "units"))
  File "C:\Users\braed\AppData\Local\Programs\Python\Python310\lib\tkinter\__init__.py", line 1967, in yview_scroll
    self.tk.call(self._w, 'yview', 'scroll', number, what)
_tkinter.TclError: invalid command name ".!toplevel6.!frame.!notebook.!frame4.!canvas"
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\braed\AppData\Local\Programs\Python\Python310\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "C:\Users\braed\Downloads\FreeScribe-main\src\FreeScribe.client\UI\SettingsWindowUI.py", line 138, in <lambda>
    self.settings_window.bind_all("<MouseWheel>", lambda e: canvas.yview_scroll(int(-1*(e.delta/120)), "units"))
  File "C:\Users\braed\AppData\Local\Programs\Python\Python310\lib\tkinter\__init__.py", line 1967, in yview_scroll
    self.tk.call(self._w, 'yview', 'scroll', number, what)
_tkinter.TclError: invalid command name ".!toplevel6.!frame.!notebook.!frame4.!canvas"

**Comment by ItsSimko** [comment]
Error was not unbinding scroll wheel events. Fixed in #73

**Comment by ItsSimko** [comment]
merged #73
